language: r
cache: packages

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
  - testthat
  - roxygen2
  - rmarkdown

warnings_are_errors: true

script: "Rscript -e 'library(devtools); check(); test()'"

notifications:
  email:
    on_success: change
    on_failure: change
